### ISSUE TITLE
Codepro font isn't applying the correct font

### ISSUE THREAD

**Issue by Scerball** [CriticalFlaw/FlawHUD.Installer#11]
Font I expect
![20200619205815_1](https://user-images.githubusercontent.com/50614660/91201428-545ed380-e6f8-11ea-8999-8dce326507f7.jpg)

Font I get
![20200825172719_1](https://user-images.githubusercontent.com/50614660/91201463-5de83b80-e6f8-11ea-9acc-4ceeb4334a97.jpg)

**Comment by CriticalFlaw** [comment]
Does it work if you install the code pro fonts? They're in resource/fonts

**Comment by Scerball** [comment]
I used the installer

**Comment by Scerball** [comment]
I can confirm it works after installing the fonts

**Comment by CriticalFlaw** [comment]
Good. I think there's a tag that can be applied to the client scheme to load custom fonts that haven't been installed. I'll look into that later.
