### ISSUE TITLE
Option to change the number of killfeed lines

### ISSUE THREAD

**Issue by randrade86** [CriticalFlaw/FlawHUD.Installer#13]
How about increase the amount of lines that display the kill feed? 4 lines is way too small.

Just to illustrate. 16 bots killed = last 4 shown. How about 7-10 lines?

![image](https://user-images.githubusercontent.com/5365488/92405033-28d1e500-f10b-11ea-9ab7-36361c6cbd82.png)

**Comment by CriticalFlaw** [comment]
Done. Added the option to set killfeed rows anywhere between 0 and 9. This change will be included in version 1.6 release.

![image](https://user-images.githubusercontent.com/6818236/93345991-7a602b00-f801-11ea-8a8b-ec89c120270b.png)
