### ISSUE TITLE
.NET error

### ISSUE THREAD

**Issue by MulverineX** [CriticalFlaw/FlawHUD.Installer#16]
When running the installer I got this error
![image](https://user-images.githubusercontent.com/12068027/104078961-efef6d00-51dd-11eb-90cc-1d9a31c81c23.png)

So I clicked yes, installed the framework downloaded from the Microsoft page, and it still appears with this error.

**Comment by CriticalFlaw** [comment]
You may have installed the NET 5 SDK and not the runtime. Do you remember which one you installed?

**Comment by MulverineX** [comment]
`windowsdesktop-runtime-3.1.10-win-x64.exe` thats the installer for NET that the prompt there sent me to

**Comment by MulverineX** [comment]
The link: https://dotnet.microsoft.com/download/dotnet-core/5.0/runtime/?utm_source=getdotnetcore&utm_medium=referral

**Comment by CriticalFlaw** [comment]
That link points to NET Core 3.1 not 5.0. Follow the link below and install the ASP.NET Core Runtime 5.0.1

https://dotnet.microsoft.com/download/dotnet/5.0

**Comment by MulverineX** [comment]
Nope still didn't work. I used this link https://dotnet.microsoft.com/download/dotnet/thank-you/runtime-aspnetcore-5.0.1-windows-x64-installer

**Comment by MulverineX** [comment]
Tried this one too https://dotnet.microsoft.com/download/dotnet/thank-you/runtime-aspnetcore-5.0.1-windows-hosting-bundle-installer

**Comment by MulverineX** [comment]
Aha! This is what I needed: https://dotnet.microsoft.com/download/dotnet/thank-you/runtime-desktop-5.0.1-windows-x64-installer
