### ISSUE TITLE
Installer doesn't actually install?

### ISSUE THREAD

**Issue by Leo40Git** [CriticalFlaw/FlawHUD.Installer#4]
For some reason, hitting the "Install" button doesn't actually install the HUD. The installer claims "FlawHUD has been successfully installed", but no `flawhud` folder exists in my custom folder, the installer's "Uninstall" and "Apply Changes" buttons are still disabled, and booting up TF2 shows that it still has the default HUD.
flawhud_app.log: [here](https://github.com/CriticalFlaw/FlawHUD.Installer/files/4746726/flawhud_app.log)

**Comment by CriticalFlaw** [comment]
Thank you for reporting this. I've released a new version (1.3.1) which fixes the problem. You should receive a notification next time you open the installer.
