### ISSUE TITLE
I can't see which options I ticked

### ISSUE THREAD

**Issue by neoxangards** [CriticalFlaw/FlawHUD.Installer#5]
So I'm having a blast using this installer to customize my HUD but the problem is I can't see which options I ticked on and off (like Spy Disguise Image, Enable Crosshairs, etc.)
Any way to fix it?
![image](https://user-images.githubusercontent.com/67174117/85186634-df70b700-b2cc-11ea-9082-5a1bf4d2395a.png)

**Comment by CriticalFlaw** [comment]
Which operating system are you using?

**Comment by CriticalFlaw** [comment]
Closing due to lack of reply from the user. The app is meant to be used in Windows 10, so if you're using an older operating system then it's likely to not work properly.
