### ISSUE TITLE
Auto-updater broke

### ISSUE THREAD

**Issue by Leo40Git** [CriticalFlaw/FlawHUD.Installer#6]
Seems like it's trying to load release "1.4.0", but the release is named "1.4".

**Comment by CriticalFlaw** [comment]
I've updated the release tag from 1.4 to 1.4.0 so it can now be detected by the updater. Weird, this wasn't an issue before without the zero at the end. Thank you for reporting it.

**Comment by Leo40Git** [comment]
```xml
    <url>https://github.com/CriticalFlaw/FlawHUD.Installer/releases/tag/1.4.0</url>
    <changelog>https://github.com/CriticalFlaw/FlawHUD.Installer/releases/tag/1.4.0</changelog>
```
I think I figured it out 😛

**Comment by CriticalFlaw** [comment]
Yeah, after updating the release tag it should now be detectable. Thanks
