### ISSUE TITLE
"sequence contains no elements"

### ISSUE THREAD

**Issue by ThyHog** [CriticalFlaw/FlawHUD.Installer#7]
this keeps happening, help?

**Comment by CriticalFlaw** [comment]
When does this happen? Could you send a screenshot?

**Comment by ThyHog** [comment]
sure.
it happens when i click anything in the bottom right button menu.
(note: i have had flawhud work before, and have uninstalled it and
reinstalled because of it not working)
and i know it's supposed to make a folder called "flawhud"
every time this happens, it says it installs.

**Comment by CriticalFlaw** [comment]
Turns out it's because the name of the variable that controls the player health has been renamed in FlawHUD. I'll revert that change which should correct the issue with the installer.

**Comment by CriticalFlaw** [comment]
Just pushed the update that corrects the player name variable. Now if you download the latest version through the installer, it should no longer show the error.

https://github.com/CriticalFlaw/FlawHUD/commit/9761d67b78c7b747f69102e10ee3bc72a14b6575

**Comment by ThyHog** [comment]
Many thanksSent on my Virgin Mobile Phone.
-------- Original message --------From: Igor <notifications@github.com> Date: 8/9/20  11:15 AM  (GMT-05:00) To: "CriticalFlaw/FlawHUD.Installer" <FlawHUD.Installer@noreply.github.com> Cc: ThyHog <jmo52173@gmail.com>, Author <author@noreply.github.com> Subject: Re: [CriticalFlaw/FlawHUD.Installer] "sequence contains no elements" (#7) 
Just pushed the update that corrects the player name variable. Now if you download the latest version through the installer, it should no longer show the error.
CriticalFlaw/FlawHUD@9761d67

**Comment by ThyHog** [comment]
soo
issue
even when i launch tf2 with the launcher, nothing changes, no errors though
