### ISSUE TITLE
Nothing changes

### ISSUE THREAD

**Issue by ThyHog** [CriticalFlaw/FlawHUD.Installer#8]
i have installed 4 different things, yet nothing changes with the game, not to mention the flawhud folder, along with it's backup
so no errors, and a no longer working hud
i miss when this worked for me, really is a great hud
![2020-08-09](https://user-images.githubusercontent.com/64565546/89737030-d5447c80-da22-11ea-958e-21cc6164b634.png)

**Comment by CriticalFlaw** [comment]
Move the installer folder to another directory and make sure you only have a single flawhud folder in your tf/custom. I think there are too many conflicts going on so the game doesn't load anything

**Comment by ThyHog** [comment]
another directory? with the installer or put it outside of custom?

**Comment by ThyHog** [comment]
![2020-08-09 (1)](https://user-images.githubusercontent.com/64565546/89737540-6f59f400-da26-11ea-9131-f8679642978a.png)
how's this? because it still isn't working...

**Comment by CriticalFlaw** [comment]
You should only have the one _flawhud_ folder in tf/custom. Remove FlawHUD-master and place FlawHUD.Installer somewhere else, it does not need to be in tf/custom to work

**Comment by ThyHog** [comment]
uhmm.... i did that
nothin
![2020-08-09 (2)](https://user-images.githubusercontent.com/64565546/89738285-33c22880-da2c-11ea-9e1f-179b97f16903.png)

**Comment by CriticalFlaw** [comment]
hmm what's inside the flawhud folder?

**Comment by ThyHog** [comment]
sound/sound.cache

**Comment by CriticalFlaw** [comment]
and that's it?

**Comment by CriticalFlaw** [comment]
ok, remove the flawhud folder - run the installer and click Install. That should hopefully correct the issue

**Comment by ThyHog** [comment]
ok one sec

**Comment by ThyHog** [comment]
uhm
nothin happened

**Comment by ThyHog** [comment]
YES I DID IT
I CHANGED ITS DIRECTORY
flawhud now has everything, testing if it actually works ffs

**Comment by ThyHog** [comment]
it worked, thank you. hope i wasn't a nuisance or anything

**Comment by CriticalFlaw** [comment]
No worries, glad it got resolved.
